version: "3.3"

services:
  db:
    image: trophy-db:latest
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: trophy-bak:latest
    depends_on:
      - db
    ports:
      - "80:8000"
