@BASE = http://127.0.0.1:4998

POST {{BASE}}/login
Content-Type: application/json

{
    "name": "lukas",
    "password": "test"
}

### get all games
GET {{BASE}}/games?year=2024

### create a new game
POST {{BASE}}/games
Content-Type: application/json

{
    "trophy_id": 1,
    "name": "asdf",
    "kind": "time",
    "user_id": 1,
    "locked": false
}

### get game with id 1
GET {{BASE}}/games/1

### update game with id 1
PUT {{BASE}}/games/1
Content-Type: application/json

{
    "trophy_id": 2,
    "name": "asdf2",
    "kind": "time"
}

### delete game with id 1
DELETE {{BASE}}/games/6
