GET http://127.0.0.1:8080/games HTTP/1.1

###

POST http://127.0.0.1:8080/games HTTP/1.1
content-type: application/json

{
    "id": 1,
    "name": "asdf",
    "kind": "time"
}

###

GET http://127.0.0.1:8080/games/1

###

PUT http://127.0.0.1:8080/games/1 HTTP/1.1
content-type: application/json

{
    "id": 2,
    "name": "asdf2",
    "kind": "time"
}

###

DELETE http://127.0.0.1:8080/games/2 HTTP/1.1