@BASE = http://127.0.0.1:4998


POST {{BASE}}/login
Content-Type: application/json

{
    "name": "lukas",
    "password": "test"
}

### evaluate trophy -> this create an xlsx-file
GET {{BASE}}/history