@BASE = http://127.0.0.1:4998
@TOKEN = asdf

POST {{BASE}}/login
Content-Type: application/json

{
    "name": "lukas",
    "password": "test"
}

### ping
GET {{BASE}}/ping
Authorization: bearer {{TOKEN}}

### reset the database
POST {{BASE}}/reset/database
Authorization: bearer {{TOKEN}}
