@BASE = http://127.0.0.1:8080
@TOKEN = asdf

POST {{BASE}}/login
Content-Type: application/json

{
    "username": "lukas",
    "password": "test"
}

### get all outcomes
GET {{BASE}}/outcomes 
Authorization: bearer {{TOKEN}}

### update outcome
PUT {{BASE}}/outcomes 
Content-Type: application/json
Authorization: bearer {{TOKEN}}

{
    "game_id": 4,
    "team_id": 4,
    "data": "100"
}

### get outcomes for team 1
GET {{BASE}}/outcomes/teams/1 
Authorization: bearer {{TOKEN}}

### get outcomes for game 1
GET {{BASE}}/outcomes/games/1 
Authorization: bearer {{TOKEN}}
