@BASE = http://127.0.0.1:5000

POST {{BASE}}/login
Content-Type: application/json

{
    "name": "lukas",
    "password": "test"
}

### get all outcomes
GET {{BASE}}/outcomes 

### update outcome
PUT {{BASE}}/outcomes 
Content-Type: application/json

{
    "game_id": 2,
    "team_id": 1,
    "data": "100"
}

### get outcomes for team 1
GET {{BASE}}/outcomes/teams/1 

### get outcomes for game 1
GET {{BASE}}/outcomes/games/1 
