@BASE = http://127.0.0.1:8080

### get all outcomes
GET {{BASE}}/outcomes 

### update outcome
PUT {{BASE}}/outcomes 
content-type: application/json

{
    "game_id": 4,
    "team_id": 4,
    "data": "100"
}

### get outcomes for team 1
GET {{BASE}}/outcomes/teams/1 

### get outcomes for game 1
GET {{BASE}}/outcomes/games/1 