@BASE = http://127.0.0.1:8080

### get all teams
GET {{BASE}}/teams

### add new team
POST {{BASE}}/teams
content-type: application/json

{
    "trophy_id": 1,
    "name": "test",
    "gender": "male"
}

### get team with id 1
GET {{BASE}}/teams/1

### update team with id 1
PUT http://127.0.0.1:8080/teams/1
content-type: application/json

{
    "trophy_id": 2,
    "name": "test2",
    "gender": "female"
}

### delete team with id 1
DELETE http://127.0.0.1:8080/teams/1