GET http://127.0.0.1:8080/teams HTTP/1.1

###

POST http://127.0.0.1:8080/teams HTTP/1.1
content-type: application/json

{
    "id": 1,
    "name": "test",
    "gender": "male",
    "points": 0
}

###

GET http://127.0.0.1:8080/teams/1

###
PUT http://127.0.0.1:8080/teams/1 HTTP/1.1
content-type: application/json

{
    "id": 2,
    "name": "test2",
    "gender": "female", 
    "points": 0
}

###
DELETE http://127.0.0.1:8080/teams/2 HTTP/1.1