@BASE = http://127.0.0.1:5000
@TOKEN = asdf

POST {{BASE}}/login
Content-Type: application/json

{
    "name": "lukas",
    "password": "test"
}

### get all teams
GET {{BASE}}/teams
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjUxNTI4NDAsImV4cCI6MTYyNTE1NTcyMCwidXNlcl9pZCI6MSwibG9naW5fc2Vzc2lvbiI6IjgyN2ExNTIyYzRjMTQ1YmJhZjMyMTk5NzQ3ZjUzYTIwIn0.ArngkK-UMJAAukPo9VWRYytV32gyG0wHzI_BaHZKeb8

### add new team
POST {{BASE}}/teams
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjUxNTI4NDAsImV4cCI6MTYyNTE1NTcyMCwidXNlcl9pZCI6MSwibG9naW5fc2Vzc2lvbiI6IjgyN2ExNTIyYzRjMTQ1YmJhZjMyMTk5NzQ3ZjUzYTIwIn0.ArngkK-UMJAAukPo9VWRYytV32gyG0wHzI_BaHZKeb8

{
    "trophy_id": 3,
    "name": "sadf",
    "gender": "male"
}

### get team with id 1
GET {{BASE}}/teams/1
Authorization: bearer {{TOKEN}}

### update team with id 1
PUT http://127.0.0.1:8080/teams/1
Content-Type: application/json
Authorization: bearer {{TOKEN}}

{
    "trophy_id": 2,
    "name": "test2",
    "gender": "female"
}

### delete team with id 1
DELETE http://127.0.0.1:8080/teams/1
Authorization: bearer {{TOKEN}}
