@BASE = http://127.0.0.1:4998
@PROD_BASE = http://asdf.edith.mlel.dev
@ID = 2

# TODO check how I can assign to TOKEN
// NOTE there might be no need for this, rest-client stores cookies apparently -> check with consecutive requests without token-header!?

@TOKEN = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjQxMTAxMzMsImV4cCI6MTYyNDExMzAxMywidXNlcl9pZCI6MSwibG9naW5fc2Vzc2lvbiI6ImY0ZTczNmVkOGM4ZDQ3ZjFiOTkwY2IwZDQ3ZWMxNDhhIn0.yuXyWgsljzLsUubAbRNxVKK0EAhnjGBa2-zWL34HlII
POST {{BASE}}/login
Content-Type: application/json

{
    "name": "lukas",
    "password": "test"
}

### log out
POST {{BASE}}/logout
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjQxODg1MzcsImV4cCI6MTYyNDE5MTQxNywidXNlcl9pZCI6MSwibG9naW5fc2Vzc2lvbiI6IjZmZTBmMmFmNjJhZTQ1Y2Y4NmI0MzYzZWQ1Yjg5YzA2In0.hOa7jbAgE21T3nQ6-JRkI2ezTayhy382jVyQNeCGcDQ

### get all users
GET {{BASE}}/users
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjQxODg1MzcsImV4cCI6MTYyNDE5MTQxNywidXNlcl9pZCI6MSwibG9naW5fc2Vzc2lvbiI6IjZmZTBmMmFmNjJhZTQ1Y2Y4NmI0MzYzZWQ1Yjg5YzA2In0.hOa7jbAgE21T3nQ6-JRkI2ezTayhy382jVyQNeCGcDQ

### get user
GET {{BASE}}/users/{{ID}}

### create new user
POST {{BASE}}/users
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjQxODg1MzcsImV4cCI6MTYyNDE5MTQxNywidXNlcl9pZCI6MSwibG9naW5fc2Vzc2lvbiI6IjZmZTBmMmFmNjJhZTQ1Y2Y4NmI0MzYzZWQ1Yjg5YzA2In0.hOa7jbAgE21T3nQ6-JRkI2ezTayhy382jVyQNeCGcDQ

{
    "name": "bernd",
    "password": "asdf",
    "role": "referee",
    "game_id": null
}

### update user
PUT {{BASE}}/users/{{ID}}
Content-Type: application/json

{
    "name": "lars",
    "password": "hermann",
    "role": "admin"
}