@BASE = http://127.0.0.1:4998
@PROD_BASE = http://asdf.edith.mlel.dev
@ID = 2

POST {{BASE}}/login
Content-Type: application/json

{
    "name": "lukas",
    "password": "test"
}

### log out
POST {{BASE}}/logout

### get all users
GET {{BASE}}/users

### get user
GET {{BASE}}/users/{{ID}}

### create new user
POST {{BASE}}/users
Content-Type: application/json

{
    "name": "bernd",
    "password": "asdf",
    "role": "referee",
    "game_id": null
}

### update user
PUT {{BASE}}/users/{{ID}}
Content-Type: application/json

{
    "name": "lars",
    "password": "hermann",
    "role": "admin"
}