[package]
name = "trophy-be"
version = "1.0.0"
authors = ["vaerl <me@lukas.run>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# basics
dotenv = "0.15"
futures = "0.3.30"
humantime = "2.1"
xlsxwriter = "0.6"
thiserror = "1.0.59"
async-trait = "0.1.80"
# logging
env_logger = "0.11.3"
log = "0.4.21"
# runtime
tokio = { version = "1.37.0", features = ["full"] }
# database
sqlx = { version = "0.7.4", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
] }
# http/rest
actix-web = "4.5.1"
actix-files = "0.6.5"
actix-service = "2.0.2"
actix-cors = "0.7"
serde = "1.0.200"
serde_json = "1.0.116"
# websockets
actix-web-actors = "4.3"
actix = "0.13.3"
# auth
jsonwebtoken = "9.3"
argon2 = "0.5.3"
rand_core = { version = "0.6.4", features = ["std"] }
chrono = { version = "0.4.38", features = ["serde"] }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
