[package]
name = "trophy-be"
version = "1.0.0"
authors = ["vaerl <lukas@mlel.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# basics
dotenv = "0.15.0"
futures = "0.3"
humantime = "2.1.0"
xlsxwriter = "0.3"
thiserror = "1.0"
async-trait = "0.1.50"
derive_responder = { path = "../derive_responder" }
# logging
env_logger = "0.8.2"
log = "0.4"
# runtime
tokio = { version = "1.6", features = ["full"] }
# database
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres", "chrono", "offline" ] }
# http/rest
actix-web = "4.0.0-beta.5"
actix-files = "0.6.0-beta.4"
actix-service = "=2.0.0-beta.5"
serde = "1.0"
serde_json = "1.0"
# websockets
actix-web-actors = "4.0.0-beta.4"
# NOTE higher versions are not supported by actix-web-actors-3(https://github.com/actix/actix-web/issues/2121)
actix = "0.11"
# auth
jsonwebtoken = "7.2.0"
argon2 = "0.2"
rand_core = { version = "0.6", features = ["std"] }
chrono = { version = "0.4", features = ["serde"]}
uuid = { version = "0.8", features = ["v4", "serde"] }

[workspace]