[package]
name = "trophy-be"
version = "1.0.0"
authors = ["vaerl <me@lukas.run>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# basics
dotenv = "0.15"
futures = "0.3"
humantime = "2.1"
xlsxwriter = "0.6"
thiserror = "1.0"
async-trait = "0.1"
# logging
env_logger = "0.11"
log = "0.4"
# runtime
tokio = { version = "1", features = ["full"] }
# database
sqlx = { version = "0.7", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
] }
# http/rest
actix-web = "4.0"
actix-files = "0.6"
actix-service = "2.0"
actix-cors = "0.7"
serde = "1.0"
serde_json = "1.0"
# websockets
actix-web-actors = "4.1"
actix = "0.13"
# auth
jsonwebtoken = "9"
argon2 = "0.5"
rand_core = { version = "0.6", features = ["std"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.1", features = ["v4", "serde"] }
